services:
  - type: web
    name: carambar-backend
    runtime: docker
    plan: free
    repo: https://github.com/FATOU27/carambar-backend
    region: frankfurt
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://<your-railway-host>:3306/<dbname>?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: <username>
      - key: SPRING_DATASOURCE_PASSWORD
        value: <password>
